In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn as skl
from sklearn.preprocessing import StandardScaler,OneHotEncoder,LabelEncoder
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction import DictVectorizer
from sklearn.metrics import accuracy_score

In [2]:
data=pd.read_csv("Desktop/netflix_titles.csv")

In [3]:
data.head(10)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...
5,80163890,TV Show,Apaches,NaN,"Alberto Ammann, Eloy Azorín, Verónica Echegui,...",Spain,"September 8, 2017",2016,TV-MA,1 Season,"Crime TV Shows, International TV Shows, Spanis...",A young journalist is forced into a life of cr...
6,70304989,Movie,Automata,Gabe Ibáñez,"Antonio Banderas, Dylan McDermott, Melanie Gri...","Bulgaria, United States, Spain, Canada","September 8, 2017",2014,R,110 min,"International Movies, Sci-Fi & Fantasy, Thrillers","In a dystopian future, an insurance adjuster f..."
7,80164077,Movie,Fabrizio Copano: Solo pienso en mi,"Rodrigo Toro, Francisco Schultz",Fabrizio Copano,Chile,"September 8, 2017",2017,TV-MA,60 min,Stand-Up Comedy,Fabrizio Copano takes audience participation t...
8,80117902,TV Show,Fire Chasers,NaN,NaN,United States,"September 8, 2017",2017,TV-MA,1 Season,"Docuseries, Science & Nature TV","As California's 2016 fire season rages, brave ..."
9,70304990,Movie,Good People,Henrik Ruben Genz,"James Franco, Kate Hudson, Tom Wilkinson, Omar...","United States, United Kingdom, Denmark, Sweden","September 8, 2017",2014,R,90 min,"Action & Adventure, Thrillers",A struggling couple can't believe their luck w...

In [4]:
dat=data.drop(["show_id"],axis=1)

In [5]:
dat.isna().sum()

type               0
title              0
director        1969
cast             570
country          476
date_added        11
release_year       0
rating            10
duration           0
listed_in          0
description        0
dtype: int64

In [6]:
dat.shape

(6234, 11)

In [7]:
dat1=dat.dropna()
print(dat1)

         type                                    title  \
0       Movie  Norm of the North: King Sized Adventure
4       Movie                             #realityhigh
6       Movie                                 Automata
7       Movie       Fabrizio Copano: Solo pienso en mi
9       Movie                              Good People
...       ...                                      ...
6142  TV Show            The Great British Baking Show
6158  TV Show  Miraculous: Tales of Ladybug & Cat Noir
6167  TV Show                             Sacred Games
6182  TV Show                         Men on a Mission
6213  TV Show                         Leyla and Mecnun

                                  director  \
0                 Richard Finn, Tim Maltby
4                         Fernando Lebrija
6                              Gabe Ibáñez
7          Rodrigo Toro, Francisco Schultz
9                        Henrik Ruben Genz
...                                    ...
6142                       Andy Devonshire
6158                         Thomas Astruc
6167  Vikramaditya Motwane, Anurag Kashyap
6182                            Jung-ah Im
6213                             Onur Ünlü

                                                   cast  \
0     Alan Marriott, Andrew Toth, Brian Dobson, Cole...
4     Nesta Cooper, Kate Walsh, John Michael Higgins...
6     Antonio Banderas, Dylan McDermott, Melanie Gri...
7                                       Fabrizio Copano
9     James Franco, Kate Hudson, Tom Wilkinson, Omar...
...                                                 ...
6142  Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...
6158  Cristina Vee, Bryce Papenbrook, Keith Silverst...
6167  Saif Ali Khan, Nawazuddin Siddiqui, Radhika Ap...
6182  Ho-dong Kang, Soo-geun Lee, Sang-min Lee, Youn...
6213  Ali Atay, Melis Birkan, Serkan Keskin, Ahmet M...

                                             country         date_added  \
0           United States, India, South Korea, China  September 9, 2019
4                                      United States  September 8, 2017
6             Bulgaria, United States, Spain, Canada  September 8, 2017
7                                              Chile  September 8, 2017
9     United States, United Kingdom, Denmark, Sweden  September 8, 2017
...                                              ...                ...
6142                                  United Kingdom    August 30, 2019
6158                      France, South Korea, Japan     August 2, 2019
6167                            India, United States    August 15, 2019
6182                                     South Korea      April 9, 2019
6213                                          Turkey     April 15, 2017

      release_year rating   duration  \
0             2019  TV-PG     90 min
4             2017  TV-14     99 min
6             2014      R    110 min
7             2017  TV-MA     60 min
9             2014      R     90 min
...            ...    ...        ...
6142          2019  TV-PG  7 Seasons
6158          2018  TV-Y7  4 Seasons
6167          2019  TV-MA  2 Seasons
6182          2019  TV-14  4 Seasons
6213          2014  TV-PG  3 Seasons

                                              listed_in  \
0                    Children & Family Movies, Comedies
4                                              Comedies
6     International Movies, Sci-Fi & Fantasy, Thrillers
7                                       Stand-Up Comedy
9                         Action & Adventure, Thrillers
...                                                 ...
6142                       British TV Shows, Reality TV
6158                    Kids' TV, TV Action & Adventure
6167  Crime TV Shows, International TV Shows, TV Dramas
6182  International TV Shows, Korean TV Shows, Stand...
6213  International TV Shows, Romantic TV Shows, TV ...

                                            description
0     Before planning an awesome wedding for his gra...
4     When nerdy high schooler Dani finally attracts...
6     In a dystopian future, an insurance adjuster f...
7     Fabrizio Copano takes audience participation t...
9     A struggling couple can't believe their luck w...
...                                                 ...
6142  A talented batch of amateur bakers face off in...
6158  When Paris is in peril, Marinette becomes Lady...
6167  A link in their pasts leads an honest cop to a...
6182  Male celebs play make-believe as high schooler...
6213  Destiny brings Mecnun and Leyla together as ne...

[3774 rows x 11 columns]

In [8]:
dat1.shape

(3774, 11)

In [9]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

In [10]:
dat1.isna().sum()

type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [11]:
dat1.head()

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
4,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...
6,Movie,Automata,Gabe Ibáñez,"Antonio Banderas, Dylan McDermott, Melanie Gri...","Bulgaria, United States, Spain, Canada","September 8, 2017",2014,R,110 min,"International Movies, Sci-Fi & Fantasy, Thrillers","In a dystopian future, an insurance adjuster f..."
7,Movie,Fabrizio Copano: Solo pienso en mi,"Rodrigo Toro, Francisco Schultz",Fabrizio Copano,Chile,"September 8, 2017",2017,TV-MA,60 min,Stand-Up Comedy,Fabrizio Copano takes audience participation t...
9,Movie,Good People,Henrik Ruben Genz,"James Franco, Kate Hudson, Tom Wilkinson, Omar...","United States, United Kingdom, Denmark, Sweden","September 8, 2017",2014,R,90 min,"Action & Adventure, Thrillers",A struggling couple can't believe their luck w...

In [12]:
x=dat1.drop(["type"],axis=1)
y=dat1.type

In [33]:
dat1.type.unique()

array(['Movie', 'TV Show'], dtype=object)

In [13]:
x.head()

,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
4,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...
6,Automata,Gabe Ibáñez,"Antonio Banderas, Dylan McDermott, Melanie Gri...","Bulgaria, United States, Spain, Canada","September 8, 2017",2014,R,110 min,"International Movies, Sci-Fi & Fantasy, Thrillers","In a dystopian future, an insurance adjuster f..."
7,Fabrizio Copano: Solo pienso en mi,"Rodrigo Toro, Francisco Schultz",Fabrizio Copano,Chile,"September 8, 2017",2017,TV-MA,60 min,Stand-Up Comedy,Fabrizio Copano takes audience participation t...
9,Good People,Henrik Ruben Genz,"James Franco, Kate Hudson, Tom Wilkinson, Omar...","United States, United Kingdom, Denmark, Sweden","September 8, 2017",2014,R,90 min,"Action & Adventure, Thrillers",A struggling couple can't believe their luck w...

In [14]:
x=x.drop(["description"],axis=1)
x.head()

,title,director,cast,country,date_added,release_year,rating,duration,listed_in
0,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies"
4,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies
6,Automata,Gabe Ibáñez,"Antonio Banderas, Dylan McDermott, Melanie Gri...","Bulgaria, United States, Spain, Canada","September 8, 2017",2014,R,110 min,"International Movies, Sci-Fi & Fantasy, Thrillers"
7,Fabrizio Copano: Solo pienso en mi,"Rodrigo Toro, Francisco Schultz",Fabrizio Copano,Chile,"September 8, 2017",2017,TV-MA,60 min,Stand-Up Comedy
9,Good People,Henrik Ruben Genz,"James Franco, Kate Hudson, Tom Wilkinson, Omar...","United States, United Kingdom, Denmark, Sweden","September 8, 2017",2014,R,90 min,"Action & Adventure, Thrillers"

In [37]:
from sklearn.preprocessing import LabelEncoder  

le = LabelEncoder()
y=le.fit_transform(y)
y

array([0, 0, 0, ..., 1, 1, 1])

In [16]:
x.country=le.fit_transform(x.country)
x.release_year=le.fit_transform(x.release_year)
x.rating=le.fit_transform(x.rating)
x.duration=le.fit_transform(x.duration)
x.listed_in=le.fit_transform(x.listed_in)
x.title=le.fit_transform(x.title)
x.director=le.fit_transform(x.director)
x.cast=le.fit_transform(x.cast)
x['date_added'] = pd.to_datetime(x['date_added'])
x['date_added'] = pd.to_numeric(x.date_added.replace('-',''))

In [17]:
x.date_added

0       1567987200000000000
4       1504828800000000000
6       1504828800000000000
7       1504828800000000000
9       1504828800000000000
               ...
6142    1567123200000000000
6158    1564704000000000000
6167    1565827200000000000
6182    1554768000000000000
6213    1492214400000000000
Name: date_added, Length: 3774, dtype: int64

In [18]:
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.3,random_state=109)

In [19]:
print(X_train)

      title  director  cast  country           date_added  release_year  \
2511   2472       221  2784      351  1435536000000000000            63
4341   3168       213  2067      114  1545782400000000000            64
5233   2355       457   600      290  1522800000000000000            62
5575   3465      1467  2213      260  1491004800000000000            64
4413    171      2204  1780      194  1545264000000000000            66
...     ...       ...   ...      ...                  ...           ...
3868   2677      2628  3025      351  1487721600000000000            61
3595   3508      1007  1653      351  1577836800000000000            17
252    2242       296  3010      149  1568419200000000000            67
4921   1879      2143  2991      149  1533168000000000000            57
4939   1389      1373  3261      351  1471564800000000000            64

      rating  duration  listed_in
2511       2       150        286
4341       4        16        218
5233       8        36        157
5575       2         7        224
4413       9       103        280
...      ...       ...        ...
3868       9       134        192
3595       0        30        118
252        6        62        159
4921       9        10        256
4939       8       163        198

[2641 rows x 9 columns]

In [20]:
from sklearn import svm

#Create a svm Classifier= svm.SVC(kernel='linear')
model=svm.SVC()
model.fit(X_train,y_train)
y_pred=model.predict(X_test)

In [29]:
from sklearn.metrics import accuracy_score,precision_score,recall_score
print("Accuracy:",accuracy_score(y_test, y_pred))
print("Precision:",precision_score(y_test, y_pred, average='weighted', labels=np.unique(y_pred)))
print("Recall:",recall_score(y_test, y_pred, average='weighted', labels=np.unique(y_pred)))

Accuracy: 0.971756398940865
Precision: 0.9717563989408651
Recall: 1.0